services:
  db:
    image: postgres:18-alpine
    container_name: yonme_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 

  auth-service:
    build:
      context: ./services/auth-service
    container_name: yonme_auth_service
    depends_on:
      - db
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./nginx/dockerfile
    container_name: yonme_nginx
    ports:
      - "80:80"
    depends_on:
      - auth-service

volumes:
  db_data: {}