

services:
  db:
    build:
      context: ./db
    container_name: yonme_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 

  client:
    build:
      context: ./client
    container_name: yonme_client
    depends_on:
      - db
    restart: always

  nginx:
    build:
      context: ./client
    container_name: yonme_nginx
    ports:
      - "80:80"
    depends_on:
      - client

volumes:
  db_data: {}