services:
  db:
    image: postgres:18-alpine
    container_name: yonme_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 
      - ./db/init:/docker-entrypoint-initdb.d

  auth-service:
    build:
      context: ./server/auth-service
    container_name: yonme_auth_service
    ports:
      - "8082:8082"
    depends_on:
      - db
    restart: always

  accounts-service:
    build:
      context: ./server/accounts-service
    container_name: yonme_accounts_service
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "8081:8081"
    depends_on:
      - db
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./nginx/dockerfile
    container_name: yonme_nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - accounts-service
      - db

volumes:
  db_data: {}